// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package db

import (
	"context"
)

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, created_at FROM admins WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAdmin = `-- name: InsertAdmin :one
INSERT INTO admins (email, password_hash) VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type InsertAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) InsertAdmin(ctx context.Context, arg InsertAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, insertAdmin, arg.Email, arg.PasswordHash)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
