// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveDevice = `-- name: ApproveDevice :one
UPDATE devices SET status = 'approved', approved_at = COALESCE(approved_at, now())
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, public_key, device_name, status, created_at, approved_at
`

func (q *Queries) ApproveDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, approveDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getApprovedDevice = `-- name: GetApprovedDevice :one
SELECT id, user_id, public_key, device_name, status, created_at, approved_at
FROM devices WHERE id = $1 AND status = 'approved'
`

func (q *Queries) GetApprovedDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getApprovedDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getApprovedDeviceForUpdate = `-- name: GetApprovedDeviceForUpdate :one
SELECT id, user_id, public_key, device_name, status, created_at, approved_at
FROM devices WHERE id = $1 AND status = 'approved'
FOR UPDATE
`

func (q *Queries) GetApprovedDeviceForUpdate(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getApprovedDeviceForUpdate, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, public_key, device_name, status, created_at, approved_at
FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getDeviceForUpdate = `-- name: GetDeviceForUpdate :one
SELECT id, user_id, public_key, device_name, status, created_at, approved_at
FROM devices WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetDeviceForUpdate(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceForUpdate, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (user_id, public_key, device_name)
VALUES ($1, $2, $3)
RETURNING id, user_id, public_key, device_name, status, created_at, approved_at
`

type InsertDeviceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	PublicKey  []byte      `json:"public_key"`
	DeviceName pgtype.Text `json:"device_name"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, insertDevice, arg.UserID, arg.PublicKey, arg.DeviceName)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, public_key, device_name, status, created_at, approved_at
FROM devices ORDER BY created_at DESC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.DeviceName,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices SET status = 'revoked'
WHERE id = $1 AND status = 'approved'
RETURNING id, user_id, public_key, device_name, status, created_at, approved_at
`

func (q *Queries) RevokeDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, revokeDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}
