// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupInvites = `-- name: CleanupInvites :execrows
DELETE FROM invite_tokens WHERE expires_at < $1 OR (used_at IS NOT NULL AND used_at < $2)
`

type CleanupInvitesParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) CleanupInvites(ctx context.Context, arg CleanupInvitesParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupInvites, arg.ExpiresAt, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invite_tokens (invite_id, token_hash, token_prefix, user_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInviteParams struct {
	InviteID    pgtype.UUID        `json:"invite_id"`
	TokenHash   []byte             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	UserID      pgtype.UUID        `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.Exec(ctx, insertInvite,
		arg.InviteID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const listInvites = `-- name: ListInvites :many
SELECT invite_id, token_prefix, user_id, expires_at, used_at, created_at
FROM invite_tokens ORDER BY created_at DESC
`

type ListInvitesRow struct {
	InviteID    pgtype.UUID        `json:"invite_id"`
	TokenPrefix string             `json:"token_prefix"`
	UserID      pgtype.UUID        `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListInvites(ctx context.Context) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.InviteID,
			&i.TokenPrefix,
			&i.UserID,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvite = `-- name: RedeemInvite :one
UPDATE invite_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) RedeemInvite(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, redeemInvite, tokenHash)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const removeInvite = `-- name: RemoveInvite :execrows
DELETE FROM invite_tokens WHERE invite_id = $1 AND used_at IS NULL
`

func (q *Queries) RemoveInvite(ctx context.Context, inviteID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeInvite, inviteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
