// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AdminSession struct {
	SessionIDHash []byte             `json:"session_id_hash"`
	AdminID       pgtype.UUID        `json:"admin_id"`
	CsrfTokenHash []byte             `json:"csrf_token_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type AuthNonce struct {
	DeviceID  pgtype.UUID        `json:"device_id"`
	Nonce     []byte             `json:"nonce"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Device struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	PublicKey  []byte             `json:"public_key"`
	DeviceName pgtype.Text        `json:"device_name"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

type InviteToken struct {
	TokenHash   []byte             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	UserID      pgtype.UUID        `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	InviteID    pgtype.UUID        `json:"invite_id"`
}
