// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nonces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupNonces = `-- name: CleanupNonces :execrows
DELETE FROM auth_nonces WHERE expires_at < $1
`

func (q *Queries) CleanupNonces(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupNonces, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNonce = `-- name: DeleteNonce :exec
DELETE FROM auth_nonces WHERE device_id = $1
`

func (q *Queries) DeleteNonce(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNonce, deviceID)
	return err
}

const getNonceForUpdate = `-- name: GetNonceForUpdate :one
SELECT device_id, nonce, expires_at FROM auth_nonces WHERE device_id = $1 FOR UPDATE
`

func (q *Queries) GetNonceForUpdate(ctx context.Context, deviceID pgtype.UUID) (AuthNonce, error) {
	row := q.db.QueryRow(ctx, getNonceForUpdate, deviceID)
	var i AuthNonce
	err := row.Scan(&i.DeviceID, &i.Nonce, &i.ExpiresAt)
	return i, err
}

const upsertNonce = `-- name: UpsertNonce :exec
INSERT INTO auth_nonces (device_id, nonce, expires_at) VALUES ($1, $2, $3)
ON CONFLICT (device_id) DO UPDATE SET nonce = EXCLUDED.nonce, expires_at = EXCLUDED.expires_at
`

type UpsertNonceParams struct {
	DeviceID  pgtype.UUID        `json:"device_id"`
	Nonce     []byte             `json:"nonce"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertNonce(ctx context.Context, arg UpsertNonceParams) error {
	_, err := q.db.Exec(ctx, upsertNonce, arg.DeviceID, arg.Nonce, arg.ExpiresAt)
	return err
}
