// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scopes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyInviteScopesToDevice = `-- name: CopyInviteScopesToDevice :exec
INSERT INTO device_scopes (device_id, scope_id)
SELECT $1, scope_id FROM invite_scopes WHERE invite_id = $2
`

type CopyInviteScopesToDeviceParams struct {
	DeviceID pgtype.UUID `json:"device_id"`
	InviteID pgtype.UUID `json:"invite_id"`
}

func (q *Queries) CopyInviteScopesToDevice(ctx context.Context, arg CopyInviteScopesToDeviceParams) error {
	_, err := q.db.Exec(ctx, copyInviteScopesToDevice, arg.DeviceID, arg.InviteID)
	return err
}

const deleteDeviceScopes = `-- name: DeleteDeviceScopes :exec
DELETE FROM device_scopes WHERE device_id = $1
`

func (q *Queries) DeleteDeviceScopes(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceScopes, deviceID)
	return err
}

const disableScope = `-- name: DisableScope :one
UPDATE scopes SET disabled_at = COALESCE(disabled_at, now())
WHERE id = $1
RETURNING id, name, disabled_at, created_at
`

func (q *Queries) DisableScope(ctx context.Context, id pgtype.UUID) (Scope, error) {
	row := q.db.QueryRow(ctx, disableScope, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const enableScope = `-- name: EnableScope :one
UPDATE scopes SET disabled_at = NULL
WHERE id = $1
RETURNING id, name, disabled_at, created_at
`

func (q *Queries) EnableScope(ctx context.Context, id pgtype.UUID) (Scope, error) {
	row := q.db.QueryRow(ctx, enableScope, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveScope = `-- name: GetActiveScope :one
SELECT id, name, disabled_at, created_at
FROM scopes WHERE id = $1 AND disabled_at IS NULL
`

func (q *Queries) GetActiveScope(ctx context.Context, id pgtype.UUID) (Scope, error) {
	row := q.db.QueryRow(ctx, getActiveScope, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScope = `-- name: GetScope :one
SELECT id, name, disabled_at, created_at
FROM scopes WHERE id = $1
`

func (q *Queries) GetScope(ctx context.Context, id pgtype.UUID) (Scope, error) {
	row := q.db.QueryRow(ctx, getScope, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeviceScope = `-- name: InsertDeviceScope :exec
INSERT INTO device_scopes (device_id, scope_id) VALUES ($1, $2)
`

type InsertDeviceScopeParams struct {
	DeviceID pgtype.UUID `json:"device_id"`
	ScopeID  pgtype.UUID `json:"scope_id"`
}

func (q *Queries) InsertDeviceScope(ctx context.Context, arg InsertDeviceScopeParams) error {
	_, err := q.db.Exec(ctx, insertDeviceScope, arg.DeviceID, arg.ScopeID)
	return err
}

const insertInviteScope = `-- name: InsertInviteScope :exec
INSERT INTO invite_scopes (invite_id, scope_id) VALUES ($1, $2)
`

type InsertInviteScopeParams struct {
	InviteID pgtype.UUID `json:"invite_id"`
	ScopeID  pgtype.UUID `json:"scope_id"`
}

func (q *Queries) InsertInviteScope(ctx context.Context, arg InsertInviteScopeParams) error {
	_, err := q.db.Exec(ctx, insertInviteScope, arg.InviteID, arg.ScopeID)
	return err
}

const insertScope = `-- name: InsertScope :one
INSERT INTO scopes (name) VALUES ($1)
RETURNING id, name, disabled_at, created_at
`

func (q *Queries) InsertScope(ctx context.Context, name string) (Scope, error) {
	row := q.db.QueryRow(ctx, insertScope, name)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveScopes = `-- name: ListActiveScopes :many
SELECT id, name, disabled_at, created_at
FROM scopes WHERE disabled_at IS NULL ORDER BY name
`

func (q *Queries) ListActiveScopes(ctx context.Context) ([]Scope, error) {
	rows, err := q.db.Query(ctx, listActiveScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scope{}
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceScopes = `-- name: ListDeviceScopes :many
SELECT s.id, s.name, s.disabled_at, s.created_at
FROM device_scopes d
JOIN scopes s ON s.id = d.scope_id
WHERE d.device_id = $1
ORDER BY s.name
`

func (q *Queries) ListDeviceScopes(ctx context.Context, deviceID pgtype.UUID) ([]Scope, error) {
	rows, err := q.db.Query(ctx, listDeviceScopes, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scope{}
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDeviceScopes = `-- name: ListEnabledDeviceScopes :many
SELECT s.name
FROM device_scopes d
JOIN scopes s ON s.id = d.scope_id
WHERE d.device_id = $1 AND s.disabled_at IS NULL
ORDER BY s.name
`

func (q *Queries) ListEnabledDeviceScopes(ctx context.Context, deviceID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnabledDeviceScopes, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInviteScopes = `-- name: ListInviteScopes :many
SELECT s.id, s.name, s.disabled_at, s.created_at
FROM invite_scopes i
JOIN scopes s ON s.id = i.scope_id
WHERE i.invite_id = $1
ORDER BY s.name
`

func (q *Queries) ListInviteScopes(ctx context.Context, inviteID pgtype.UUID) ([]Scope, error) {
	rows, err := q.db.Query(ctx, listInviteScopes, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scope{}
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopes = `-- name: ListScopes :many
SELECT id, name, disabled_at, created_at
FROM scopes ORDER BY name
`

func (q *Queries) ListScopes(ctx context.Context) ([]Scope, error) {
	rows, err := q.db.Query(ctx, listScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scope{}
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
