// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupSessions = `-- name: CleanupSessions :execrows
DELETE FROM admin_sessions WHERE expires_at < $1
`

func (q *Queries) CleanupSessions(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM admin_sessions WHERE session_id_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionIDHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionIDHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT session_id_hash, admin_id, csrf_token_hash, created_at, expires_at
FROM admin_sessions WHERE session_id_hash = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, sessionIDHash []byte) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getSession, sessionIDHash)
	var i AdminSession
	err := row.Scan(
		&i.SessionIDHash,
		&i.AdminID,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO admin_sessions (session_id_hash, admin_id, csrf_token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	SessionIDHash []byte             `json:"session_id_hash"`
	AdminID       pgtype.UUID        `json:"admin_id"`
	CsrfTokenHash []byte             `json:"csrf_token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.SessionIDHash,
		arg.AdminID,
		arg.CsrfTokenHash,
		arg.ExpiresAt,
	)
	return err
}
